library(readxl)
library(tidyverse)
library(ggplot2)
library(highcharter)
library(plotly)
library(stringr)
library(viridis)
library(gridExtra)
library(tidyverse)
library(highcharter)
library(plotly)
library(htmltools)
library(purrr)
library(rjson)
library(jsonlite)
library(tidytext)
library(ggraph)
library(igraph)


data <- fromJSON("../data/train.json")
data <- as.data.frame(data)
head(flatten(data))
